import { emptyTask, PROPOSAL_STATUS, TASK_STATUS } from './models.js';
import { fallbackAnalyzeTask } from './services/ai.js';
import { levelLabel, scoreTask } from './services/scoring.js';
import { loadStore, resetStore, saveStore } from './store.js';

let store = loadStore();
let draft = emptyTask('draft-current');
let analysis = null;
let role = store.currentRole || 'business';
let aiState = 'idle';
let aiError = '';
let flashMessage = '';

const app = document.querySelector('#app');
const route = () => window.location.hash.replace(/^#\/?/, '') || 'home';
const navigate = (path) => { window.location.hash = `#/${path}`; };
const esc = (value = '') => String(value).replace(/[&<>"']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' }[char]));
const scoreClass = (score) => score >= 90 ? 'priority' : score >= 70 ? 'ready' : score >= 40 ? 'working' : 'draft';
const taskById = (id) => store.tasks.find((task) => task.id === id);
const teamById = (id) => store.teams.find((team) => team.id === id);
async function requestAI(payload) { const response = await fetch('/api/ai/analyze', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }); if (!response.ok) throw new Error(`AI endpoint ${response.status}`); return response.json(); }

function header() {
  return `<header class="topbar"><a class="brand" href="#/home"><span class="brand-mark">S</span><span>Sana <em>Hub</em></span></a><nav><a class="${route() === 'home' ? 'active' : ''}" href="#/home">Главная</a>${role === 'business' ? `<a class="${route() === 'business/dashboard' ? 'active' : ''}" href="#/business/dashboard">Дашборд</a><a class="${route() === 'business/intake' || route() === 'business/card' ? 'active' : ''}" href="#/business/intake">Создать задачу</a><a class="${route() === 'business/proposals' ? 'active' : ''}" href="#/business/proposals">Предложения <span class="nav-count">${store.proposals.filter((p) => p.status === 'pending').length}</span></a>` : `<a class="${route() === 'catalog' || route().startsWith('task/') ? 'active' : ''}" href="#/catalog">Каталог задач</a>`}<a class="${route() === 'profile' ? 'active' : ''}" href="#/profile">Профиль</a></nav><div class="role-switch"><span>Сменить роль</span><button class="${role === 'business' ? 'selected' : ''}" data-role="business">Бизнес</button><button class="${role === 'student' ? 'selected' : ''}" data-role="student">Студент</button></div></header>`;
}
function page(title, subtitle, content) { return `${header()}<main class="page"><div class="page-heading"><p class="eyebrow">AI SANA CHALLENGE HUB</p><h1>${title}</h1><p class="muted">${subtitle}</p></div>${content}</main>`; }
function scoreBadge(task) { return `<span class="score-badge ${scoreClass(task.score)}"><strong>${task.score}</strong>/100 · ${levelLabel[task.readinessLevel]}</span>`; }

function renderHome() {
  return `${header()}<main class="landing"><section class="landing-hero"><p class="eyebrow">AI SANA CHALLENGE HUB</p><h1>От бизнес-задачи<br><span>к реальному решению</span></h1><p class="landing-copy">Бизнес формулирует задачу. AI помогает уточнить её. Студенты и фрилансеры находят реальные задачи и предлагают решения.</p><div class="landing-actions"><a class="primary" href="#/onboarding/business">Я представитель бизнеса →</a><a class="secondary" href="#/onboarding/student">Я студент / фрилансер</a></div></section><section class="flow-strip">${['Опишите задачу', 'Уточните её с AI', 'Получите рейтинг', 'Опубликуйте', 'Получите предложения'].map((text, index) => `<div><span>${index + 1}</span><strong>${text}</strong></div>`).join('')}</section></main>`;
}

function renderOnboarding(type) {
  const isBusiness = type === 'business';
  const profile = store.profiles?.[type] || {};
  const fields = isBusiness ? [['name', 'Имя', 'Айдар', true], ['company', 'Название компании', 'Astana Coffee', true], ['industry', 'Отрасль', 'HoReCa', true], ['contact', 'Контакт / email', 'aidar@example.com', true], ['interactionFormat', 'Формат взаимодействия', 'Онлайн-встречи и Telegram', true]] : [['name', 'Имя', 'Батыр', true], ['team', 'Название команды', 'YOLO Team', false], ['skills', 'Навыки', 'Python, Web, AI', true], ['technologies', 'Технологии', 'React, FastAPI, Python', true], ['interests', 'Интересы / направления', 'AI, аналитика, автоматизация', true], ['portfolio', 'GitHub или портфолио', 'https://github.com/example', false]];
  return page(isBusiness ? 'Профиль представителя бизнеса' : 'Профиль студента / фрилансера', isBusiness ? 'Расскажите о компании — эти данные помогут студентам понимать контекст и связываться с вами.' : 'Можно работать самостоятельно или указать команду. Профиль будет доступен при отправке предложений.', `<div class="onboarding-layout"><form id="onboarding-form" data-profile-type="${type}" class="panel onboarding-form"><div class="panel-tag">Простой onboarding · без пароля</div><div class="profile-form-grid">${fields.map(([name, label, placeholder, required]) => `<label class="field"><span>${label}${required ? ' *' : ''}</span>${name === 'interactionFormat' || name === 'skills' || name === 'technologies' || name === 'interests' ? `<textarea name="${name}" rows="3" ${required ? 'required' : ''} placeholder="${placeholder}">${esc(profile[name] || '')}</textarea>` : `<input name="${name}" value="${esc(profile[name] || '')}" ${required ? 'required' : ''} placeholder="${placeholder}" ${name === 'contact' ? 'type="email"' : name === 'portfolio' ? 'type="url"' : ''} />`}</label>`).join('')}</div><div id="onboarding-error" class="error-box" hidden>Заполните обязательные поля.</div><button class="primary full" type="submit">Сохранить профиль и продолжить →</button></form><aside class="panel onboarding-note"><div class="spark">✦</div><h2>Только данные для MVP</h2><p class="muted">Без регистрации, паролей и сложных ролей. Профиль сохраняется локально в браузере и остаётся после обновления страницы.</p><a class="text-link" href="#/home">← Вернуться на главную</a></aside></div>`);
}

function renderBusinessDashboard() {
  const profile = store.profiles?.business;
  if (!profile) return renderOnboarding('business');
  const tasks = store.tasks.filter((task) => task.status === TASK_STATUS.PUBLISHED);
  const recent = tasks.slice(0, 3);
  return page(`Здравствуйте, ${esc(profile.name)}`, `${esc(profile.company)} · ${esc(profile.industry)}`, `<section class="metric-grid"><article class="panel metric-card"><span>Опубликовано задач</span><strong>${tasks.length}</strong></article><article class="panel metric-card"><span>Всего предложений</span><strong>${store.proposals.length}</strong></article><article class="panel metric-card"><span>На рассмотрении</span><strong>${store.proposals.filter((proposal) => proposal.status === 'pending').length}</strong></article></section><section class="dashboard-head"><div><p class="panel-tag">Последние задачи</p><h2>Ваши бизнес-задачи</h2></div><a class="primary" href="#/business/intake">Создать новую задачу →</a></section><div class="catalog-grid">${recent.length ? recent.map(taskCard).join('') : '<div class="panel empty-state"><h2>Пока нет задач</h2><p class="muted">Создайте первую задачу и уточните её с AI.</p></div>'}</div>`);
}

function renderProfile() {
  const profile = store.profiles?.[role];
  if (!profile) return renderOnboarding(role);
  const entries = role === 'business' ? [['Имя', profile.name], ['Компания', profile.company], ['Отрасль', profile.industry], ['Контакт', profile.contact], ['Формат взаимодействия', profile.interactionFormat]] : [['Имя', profile.name], ['Команда', profile.team || 'Фрилансер'], ['Навыки', profile.skills], ['Технологии', profile.technologies], ['Интересы', profile.interests], ['GitHub / портфолио', profile.portfolio || 'Не указано']];
  return page('Профиль', role === 'business' ? 'Данные представителя бизнеса' : 'Данные студента / фрилансера', `<section class="panel profile-card"><div class="profile-avatar">${esc(profile.name?.[0] || '?')}</div><div><p class="panel-tag">${role === 'business' ? 'Business profile' : 'Student profile'}</p><h2>${esc(profile.name)}</h2><div class="profile-details">${entries.map(([label, value]) => `<div><span>${label}</span><p>${esc(value)}</p></div>`).join('')}</div><a class="secondary" href="#/onboarding/${role}">Редактировать профиль</a></div></section>`);
}

function renderIntake() {
  const questions = analysis?.questions || [];
  const card = analysis?.suggestedCard || draft;
  const scored = scoreTask(card);
  const error = aiError ? `<div class="error-box">${esc(aiError)}</div>` : '';
  const buttonLabel = aiState === 'loading' ? 'AI анализирует задачу…' : 'Проанализировать с AI <span>→</span>';
  const warning = analysis?.warning ? `<div class="warning-box"><strong>Fallback mode</strong><span>${esc(analysis.warning)}</span><button class="secondary compact" data-action="retry-ai">Повторить AI-запрос</button></div>` : '';
  const insight = aiState === 'loading' ? `<div class="loading-state"><div class="loading-orb">✦</div><h2>${analysis ? 'AI формирует карточку задачи…' : 'AI анализирует заполненность задачи…'}</h2><p class="muted">Проверяем известные данные и ищем реальные пробелы.</p></div>` : analysis ? `<div class="panel-tag mint">AI-разбор · ${analysis.source === 'openai' ? 'OpenAI API' : 'fallback'}</div>${warning}<h2>Нужно уточнить ${analysis.missingFields.length} полей</h2><p class="muted">Ответьте на вопросы прямо в форме — они попадут в редактируемый черновик.</p><div class="question-list">${questions.map((question, index) => `<label class="question question-field"><span>${String(index + 1).padStart(2, '0')}</span><textarea data-question="${esc(question.field)}" rows="2" placeholder="Введите ответ или оставьте пустым">${esc(analysis.answers?.[question.field] || '')}</textarea><small><b>${esc(question.field)}</b> · ${esc(question.text)}</small></label>`).join('')}</div><button class="secondary full" data-action="form-card">Сформировать карточку задачи <span>→</span></button>` : `<div class="empty-insight"><div class="spark">✦</div><h2>Здесь появится AI-разбор</h2><p class="muted">Sana найдёт пробелы в описании, предложит вопросы и подготовит редактируемый черновик карточки.</p><div class="mini-metrics"><span><b>3+</b> вопроса</span><span><b>0–100</b> рейтинг</span><span><b>100%</b> контроль бизнеса</span></div></div>`;
  return page('Превратите идею в понятную задачу', 'Сначала коротко опишите потребность бизнеса. Sana задаст вопросы и поможет собрать карточку, но финальное решение остаётся за вами.', `<section class="stepper"><span class="done">01 Описание</span><i></i><span class="${aiState === 'loading' || analysis ? 'done' : ''}">02 AI-анализ</span><i></i><span class="${analysis ? 'done' : ''}">03 Вопросы</span><i></i><span>04 Карточка</span></section><div class="grid two-col"><section class="panel hero-panel"><div class="panel-tag">Шаг 1 · Черновик</div><h2>Что нужно решить?</h2><p class="muted">Опишите проблему в 1–3 предложениях. Не нужно сразу знать все детали.</p>${error}<textarea id="draft-input" rows="6" placeholder="Например: хотим сократить списания продуктов в наших кофейнях...">${esc(draft.description)}</textarea><button class="primary full" data-action="analyze" ${aiState === 'loading' ? 'disabled' : ''}>${buttonLabel}</button><p class="tiny">Запрос идёт через backend: OpenAI API используется при настройке, а fallback — только при отсутствии конфигурации или ошибке. Неподтверждённые данные не публикуются.</p></section><section class="panel insight-panel">${insight}</section></div>${analysis ? `<section class="panel next-card"><div><p class="panel-tag">Следующий шаг</p><h2>Соберите карточку и поднимите рейтинг</h2><p class="muted">Сейчас ${scored.score}/100. Добавьте ответы, чтобы score вырос.</p></div><div class="score-ring ${scoreClass(scored.score)}"><strong>${scored.score}</strong><span>/100</span></div></section>` : ''}</section>`);
}

const fieldMeta = [['title', 'Название задачи', 'Короткий заголовок'], ['context', 'Контекст', 'Что происходит сейчас?'], ['need', 'Потребность / проблема', 'Что нужно изменить?'], ['users', 'Целевые пользователи', 'Кто будет пользоваться результатом?'], ['data', 'Данные и материалы', 'Что уже доступно команде?'], ['constraints', 'Ограничения', 'Сроки, бюджет, технологии, безопасность'], ['expectedResult', 'Ожидаемый результат', 'Что должна получить компания?'], ['successCriteria', 'Критерии успеха', 'Как измерим результат?'], ['businessContact', 'Контакт бизнеса', 'К кому обращаться по задаче?'], ['interactionFormat', 'Формат взаимодействия', 'Как команда получает обратную связь?']];
function renderCard() { const card = analysis?.suggestedCard || draft; const scored = scoreTask(card); return page('Соберите карточку задачи', 'Все поля редактируемы. Заполненность пересчитывается после каждого изменения.', `<section class="stepper"><span class="done">01 Описание</span><i></i><span class="done">02 AI-анализ</span><i></i><span class="done">03 Вопросы</span><i></i><span class="done">04 Карточка</span></section><div class="grid card-layout"><section class="panel card-form"><div class="panel-head"><div><p class="panel-tag">Редактируемый черновик · не подтверждён</p><h2>${esc(card.title || 'Новая задача')}</h2></div><span class="ai-chip">✦ AI draft</span></div><div class="form-grid">${fieldMeta.map(([key, label, placeholder]) => `<label class="field"><span>${label}</span><textarea data-field="${key}" rows="${key === 'title' ? 2 : 3}" placeholder="${card[key] ? placeholder : 'Требуется уточнение'}">${esc(card[key])}</textarea></label>`).join('')}</div><div class="form-actions"><button class="secondary" data-action="back-intake">← Вернуться к вопросам</button><button class="primary" data-action="save-card">Сохранить изменения</button></div></section><aside class="score-panel"><p class="panel-tag">Готовность</p><div class="big-score ${scoreClass(scored.score)}"><strong>${scored.score}</strong><span>/100</span></div><span class="level-pill ${scoreClass(scored.score)}">${levelLabel[scored.readinessLevel]}</span><div class="breakdown">${scored.breakdown.map((item) => `<div class="breakdown-row"><span>${item.label}</span><b>${item.points}/${item.max}</b><div class="bar"><i style="width:${(item.points / item.max) * 100}%"></i></div></div>`).join('')}</div><div class="missing"><b>Что усилить</b>${scored.missing.length ? `<ul>${scored.missing.map((item) => `<li>${item.label}</li>`).join('')}</ul>` : '<p>Все ключевые поля заполнены.</p>'}</div><button class="primary full" data-action="publish">Подтвердить карточку</button></aside></div>`); }
function taskCard(task) { return `<article class="task-card"><div class="task-top"><span class="topic">${esc(task.topic)}</span>${scoreBadge(task)}</div><h3>${esc(task.title)}</h3><p>${esc(task.need || task.description)}</p><div class="task-meta"><span>◷ ${task.expectedResult ? 'Есть результат' : 'Нужны детали'}</span><span>◉ ${store.proposals.filter((p) => p.taskId === task.id).length} предложений</span></div><a class="text-link" href="#/task/${task.id}">Открыть задачу →</a></article>`; }
function renderCatalog() { const tasks = store.tasks.filter((task) => task.status === TASK_STATUS.PUBLISHED).sort((a, b) => b.score - a.score); return page('Каталог задач', 'Открытые задачи от бизнеса. Любая команда может изучить задачу и отправить предложение.', `<div class="catalog-toolbar"><div><strong>${tasks.length} задач</strong><span class="muted"> · сортировка по готовности</span></div><div class="filters"><select id="topic-filter"><option value="all">Все темы</option>${[...new Set(tasks.map((task) => task.topic))].map((topic) => `<option>${esc(topic)}</option>`).join('')}</select><select id="level-filter"><option value="all">Все уровни</option>${Object.entries(levelLabel).map(([key, label]) => `<option value="${key}">${label}</option>`).join('')}</select></div></div><div id="catalog-grid" class="catalog-grid">${tasks.map(taskCard).join('')}</div>`); }
function renderTask(id) { const task = taskById(id); if (!task) return page('Задача не найдена', '', `<div class="panel empty-state"><h2>Такой задачи нет</h2><a class="text-link" href="#/catalog">Вернуться в каталог →</a></div>`); const proposals = store.proposals.filter((proposal) => proposal.taskId === id); return page(task.title, `${task.topic} · опубликовано для студенческих команд`, `<div class="task-detail-layout"><section><a class="back-link" href="#/catalog">← Назад в каталог</a><div class="panel detail-panel"><div class="task-top"><span class="topic">${esc(task.topic)}</span>${scoreBadge(task)}</div><p class="lead">${esc(task.need)}</p><div class="detail-fields">${[['context','Контекст'], ['users','Для кого'], ['data','Данные и материалы'], ['constraints','Ограничения'], ['expectedResult','Ожидаемый результат'], ['successCriteria','Критерии успеха'], ['businessContact','Контакт бизнеса'], ['interactionFormat','Формат взаимодействия']].map(([key, label]) => `<div><span>${label}</span><p>${esc(task[key] || 'Требуется уточнение')}</p></div>`).join('')}</div></div><section class="panel proposal-panel"><p class="panel-tag">Отклик команды</p><h2>Есть идея? Предложите решение</h2><form id="proposal-form" data-task-id="${task.id}"><label class="field"><span>Команда</span><select name="teamId" required>${store.teams.map((team) => `<option value="${team.id}">${esc(team.name)}</option>`).join('')}</select></label><label class="field"><span>Идея решения</span><textarea name="solutionIdea" required rows="3" placeholder="Какой подход предлагаете?"></textarea></label><label class="field"><span>План</span><textarea name="plan" required rows="3" placeholder="Какие шаги пройдёт команда?"></textarea></label><div class="form-grid three"><label class="field"><span>Срок</span><input name="duration" required placeholder="3 недели" /></label><label class="field wide"><span>Ссылка на прототип</span><input name="prototypeUrl" type="url" required placeholder="https://..." /></label></div><button class="primary" type="submit">Отправить предложение →</button></form></section></section><aside class="panel side-summary"><p class="panel-tag">Готовность задачи</p><div class="big-score ${scoreClass(task.score)}"><strong>${task.score}</strong><span>/100</span></div><p class="muted">${levelLabel[task.readinessLevel]} · бизнес уже подтвердил карточку</p><div class="proposal-count"><strong>${proposals.length}</strong><span>предложений уже отправлено</span></div><p class="tiny">Решение о выборе команды всегда принимает бизнес вручную.</p></aside></div>`); }
function renderProposals() { return page('Предложения команд', 'Здесь бизнес вручную сравнивает отклики. Sana не выбирает команду автоматически.', `<div class="proposal-list">${store.proposals.map((proposal) => { const task = taskById(proposal.taskId); const team = teamById(proposal.teamId); return `<article class="panel proposal-row"><div class="proposal-head"><div><span class="topic">${esc(team?.name || 'Команда')}</span><h2>${esc(task?.title || 'Задача')}</h2></div><span class="status ${proposal.status}">${proposal.status === 'accepted' ? 'Принято' : proposal.status === 'rejected' ? 'Отклонено' : 'На рассмотрении'}</span></div><div class="proposal-content"><div><span>Идея</span><p>${esc(proposal.solutionIdea)}</p></div><div><span>План</span><p>${esc(proposal.plan)}</p></div><div><span>Срок</span><p>${esc(proposal.duration)} · <a href="${esc(proposal.prototypeUrl)}" target="_blank" rel="noreferrer">прототип ↗</a></p></div></div>${proposal.status === 'pending' ? `<div class="proposal-actions"><button class="secondary danger" data-action="reject" data-proposal-id="${proposal.id}">Отклонить</button><button class="primary" data-action="accept" data-proposal-id="${proposal.id}">Принять команду</button></div>` : ''}</article>`; }).join('')}</div>`); }

function render() { const current = route(); if (current === 'home') app.innerHTML = renderHome(); else if (current.startsWith('onboarding/')) app.innerHTML = renderOnboarding(current.split('/')[1] === 'business' ? 'business' : 'student'); else if (current === 'business/dashboard') app.innerHTML = renderBusinessDashboard(); else if (current === 'profile') app.innerHTML = renderProfile(); else if (current === 'catalog') app.innerHTML = renderCatalog(); else if (current.startsWith('task/')) app.innerHTML = renderTask(current.split('/')[1]); else if (current === 'business/card') app.innerHTML = renderCard(); else if (current === 'business/proposals') app.innerHTML = renderProposals(); else app.innerHTML = renderIntake(); if (flashMessage) { app.querySelector('main')?.insertAdjacentHTML('afterbegin', `<div class="success-box">✓ ${esc(flashMessage)}</div>`); flashMessage = ''; } bindEvents(); }
function bindEvents() {
  document.querySelectorAll('[data-role]').forEach((button) => button.addEventListener('click', () => { role = button.dataset.role; store.currentRole = role; saveStore(store); navigate(store.profiles?.[role] ? (role === 'business' ? 'business/dashboard' : 'catalog') : `onboarding/${role}`); }));
  document.querySelectorAll('a[href="#/business/intake"]').forEach((link) => link.addEventListener('click', () => { if (route() === 'business/dashboard') { const profile = store.profiles?.business; draft = emptyTask('draft-current'); if (profile) { draft.businessContact = `${profile.name}, ${profile.contact}`; draft.interactionFormat = profile.interactionFormat; } analysis = null; aiError = ''; aiState = 'idle'; } }));
  document.querySelector('#onboarding-form')?.addEventListener('submit', (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); const type = event.currentTarget.dataset.profileType; const profile = Object.fromEntries([...form.entries()].map(([key, value]) => [key, String(value).trim()])); if (!event.currentTarget.checkValidity()) { document.querySelector('#onboarding-error').hidden = false; return; } store.profiles ||= { business: null, student: null }; store.profiles[type] = profile; store.currentRole = type; role = type; if (type === 'student') { const team = { id: 'profile-student', name: profile.team || profile.name, interests: profile.interests, skills: profile.skills, technologies: profile.technologies, portfolio: profile.portfolio }; store.teams = [team, ...store.teams.filter((item) => item.id !== team.id)]; } else { draft.businessContact ||= `${profile.name}, ${profile.contact}`; draft.interactionFormat ||= profile.interactionFormat; } saveStore(store); navigate(type === 'business' ? 'business/dashboard' : 'catalog'); });
  document.querySelector('[data-action="analyze"]')?.addEventListener('click', async () => { const value = document.querySelector('#draft-input').value.trim(); if (!value) { aiError = 'Сначала опишите задачу.'; render(); return; } aiError = ''; aiState = 'loading'; render(); try { draft = { ...draft, description: value }; analysis = await requestAI({ description: value, currentCard: draft }); analysis.answers = {}; draft = { ...draft, ...analysis.suggestedCard }; aiState = 'idle'; render(); } catch { aiState = 'idle'; aiError = 'AI-сервис недоступен. Проверьте сервер или попробуйте fallback ещё раз.'; analysis = fallbackAnalyzeTask({ description: value, currentCard: draft }); analysis.answers = {}; draft = { ...draft, ...analysis.suggestedCard }; render(); } });
  document.querySelector('[data-action="retry-ai"]')?.addEventListener('click', () => document.querySelector('[data-action="analyze"]')?.click());
  document.querySelector('[data-action="form-card"]')?.addEventListener('click', async () => { const answers = {}; document.querySelectorAll('[data-question]').forEach((input) => { answers[input.dataset.question] = input.value.trim(); }); analysis.answers = answers; aiState = 'loading'; render(); try { const result = await requestAI({ description: draft.description, currentCard: analysis.suggestedCard, previousQuestions: analysis.questions, answers }); analysis = { ...result, answers }; draft = { ...draft, ...result.suggestedCard }; aiState = 'idle'; navigate('business/card'); } catch { aiState = 'idle'; analysis = { ...fallbackAnalyzeTask({ description: draft.description, currentCard: analysis.suggestedCard, answers }), answers }; draft = { ...draft, ...analysis.suggestedCard }; aiError = 'OpenAI API недоступен, поэтому применён локальный fallback.'; navigate('business/card'); } });
  document.querySelector('[data-action="back-intake"]')?.addEventListener('click', () => navigate('business/intake'));
  document.querySelectorAll('[data-field]').forEach((input) => input.addEventListener('input', () => { if (analysis) analysis.suggestedCard[input.dataset.field] = input.value; else draft[input.dataset.field] = input.value; renderCardLive(); }));
  document.querySelector('[data-action="save-card"]')?.addEventListener('click', () => { draft = analysis?.suggestedCard || draft; alert('Изменения сохранены. Рейтинг обновлён.'); render(); });
  document.querySelector('[data-action="publish"]')?.addEventListener('click', () => { const card = { ...(analysis?.suggestedCard || draft) }; const scored = scoreTask(card); if (!card.title || !card.need) { aiError = 'Заполните название и потребность.'; render(); return; } const published = { ...card, ...scored, status: TASK_STATUS.PUBLISHED, confirmed: true, topic: card.topic || 'Другое' }; store.tasks = [published, ...store.tasks.filter((task) => task.id !== published.id)]; saveStore(store); flashMessage = 'Карточка подтверждена и опубликована в каталоге.'; navigate('catalog'); });
  document.querySelector('#proposal-form')?.addEventListener('submit', (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); store.proposals.unshift({ id: `proposal-${Date.now()}`, taskId: event.currentTarget.dataset.taskId, teamId: form.get('teamId'), solutionIdea: form.get('solutionIdea'), plan: form.get('plan'), duration: form.get('duration'), prototypeUrl: form.get('prototypeUrl'), status: PROPOSAL_STATUS.PENDING, createdAt: new Date().toISOString() }); saveStore(store); alert('Предложение отправлено бизнесу.'); navigate('business/proposals'); });
  document.querySelectorAll('[data-action="accept"], [data-action="reject"]').forEach((button) => button.addEventListener('click', () => { const proposal = store.proposals.find((item) => item.id === button.dataset.proposalId); if (!proposal) return; proposal.status = button.dataset.action === 'accept' ? PROPOSAL_STATUS.ACCEPTED : PROPOSAL_STATUS.REJECTED; saveStore(store); render(); }));
  document.querySelector('#topic-filter')?.addEventListener('change', filterCatalog); document.querySelector('#level-filter')?.addEventListener('change', filterCatalog);
}
function renderCardLive() { const existing = document.querySelector('.score-panel'); if (!existing) return; const scored = scoreTask(analysis?.suggestedCard || draft); const badge = existing.querySelector('.big-score'); if (badge) badge.innerHTML = `<strong>${scored.score}</strong><span>/100</span>`; }
function filterCatalog() { const topic = document.querySelector('#topic-filter').value; const level = document.querySelector('#level-filter').value; const tasks = store.tasks.filter((task) => task.status === TASK_STATUS.PUBLISHED && (topic === 'all' || task.topic === topic) && (level === 'all' || task.readinessLevel === level)).sort((a, b) => b.score - a.score); document.querySelector('#catalog-grid').innerHTML = tasks.length ? tasks.map(taskCard).join('') : '<div class="panel empty-state"><h2>Ничего не найдено</h2><p class="muted">Попробуйте изменить фильтры.</p></div>'; }

window.addEventListener('hashchange', render);
window.addEventListener('storage', () => { store = loadStore(); render(); });
window.resetSanaDemo = () => { store = resetStore(); analysis = null; draft = emptyTask('draft-current'); render(); };
render();
