import { makeProposal, makeTeam, emptyTask, TASK_STATUS } from './models.js';
import { scoreTask } from './services/scoring.js';
const task = (id, values) => { const result = { ...emptyTask(id), ...values, status: TASK_STATUS.PUBLISHED, confirmed: true }; const scored = scoreTask(result); return { ...result, score: scored.score, readinessLevel: scored.readinessLevel }; };
export const seedData = {
  tasks: [
    task('task-1', { title: 'Умный учёт списания продуктов', description: 'Снизить списания продуктов в сети кофеен.', context: 'Пять городских кофеен ежедневно списывают готовую продукцию.', need: 'Нужен прогноз спроса и подсказки по объёму производства.', users: 'Управляющие и сотрудники кофеен.', data: 'Продажи по дням, остатки и журнал списаний за 12 месяцев.', constraints: 'Первый прототип за 3 недели, без изменения кассовой системы.', expectedResult: 'Прототип дашборда с прогнозом и рекомендациями.', successCriteria: 'Снизить списания на 15% на тестовой точке.', businessContact: 'Айдана, aidana@example.test', interactionFormat: 'Еженедельный созвон.', topic: 'Retail' }),
    task('task-2', { title: 'Навигация для посетителей кампуса', description: 'Студентам сложно быстро найти нужный корпус.', context: 'Кампус состоит из 12 корпусов и нескольких закрытых проходов.', need: 'Сделать понятную навигацию для новых студентов.', users: 'Первокурсники и гости кампуса.', data: 'План кампуса, расписание доступности входов.', constraints: 'Работа без регистрации и геолокации в первой версии.', expectedResult: 'Интерактивная карта маршрутов.', successCriteria: '80% тестовых пользователей находят корпус за 2 минуты.', businessContact: 'Марат, marat@example.test', interactionFormat: 'Чат в рабочие дни.', topic: 'EdTech' }),
    task('task-3', { title: 'Каталог локальных фермеров', description: 'Покупателям трудно сравнивать локальные продукты.', context: 'Фермеры публикуют предложения в разных каналах.', need: 'Собрать предложения в единый каталог.', users: 'Городские семьи и небольшие магазины.', data: 'Прайсы, фотографии, адреса точек выдачи.', constraints: 'Только открытые данные и ручная модерация.', expectedResult: 'Каталог с фильтрами по продукту и району.', successCriteria: 'В каталоге 50 поставщиков за первый месяц.', businessContact: 'Дана, dana@example.test', interactionFormat: 'Две встречи в месяц.', topic: 'AgTech' }),
    task('task-4', { title: 'Аналитика загруженности спортзала', description: 'Посетители приходят в часы пик и ждут тренажёры.', context: 'У спортзала есть данные проходов по времени.', need: 'Показать менее загруженные часы.', users: 'Посетители и администратор спортзала.', data: 'Анонимная статистика проходов за 6 месяцев.', constraints: 'Не собирать персональные данные.', expectedResult: 'Публичный график загруженности.', successCriteria: 'Снизить среднее время ожидания на 20%.', businessContact: 'Руслан, ruslan@example.test', interactionFormat: 'Онлайн-форма обратной связи.', topic: 'HealthTech' }),
    task('task-5', { title: 'Помощник для сортировки обращений', description: 'Команда поддержки вручную сортирует входящие обращения.', context: 'Каждый день поступает около 300 обращений в трёх категориях.', need: 'Ускорить первичную классификацию обращений.', users: 'Операторы поддержки.', data: 'Обезличенный архив обращений и категории.', constraints: 'Оператор подтверждает рекомендацию категории.', expectedResult: 'Прототип формы с подсказкой категории.', successCriteria: '70% обращений получают верную подсказку.', businessContact: 'Ерлан, erlan@example.test', interactionFormat: 'Демо раз в неделю.', topic: 'AI' }),
  ],
  teams: [
    makeTeam('team-1', 'Data Nomads', 'AI, аналитика, бизнес', 'Python, ML, dashboards', 'Python, FastAPI, Metabase'), makeTeam('team-2', 'Qadam Studio', 'EdTech, UX', 'UX research, frontend', 'Figma, React, TypeScript'), makeTeam('team-3', 'Green Byte', 'AgTech, устойчивость', 'data viz, product', 'Python, Supabase, D3.js'), makeTeam('team-4', 'Nomad Mobile', 'мобильные продукты', 'mobile, prototyping', 'Flutter, Firebase'), makeTeam('team-5', 'Koktem Lab', 'AI, автоматизация', 'NLP, backend', 'Python, FastAPI, Docker'),
  ],
  proposals: [
    makeProposal('proposal-1', 'task-1', 'team-1', 'Прогноз спроса по SKU и дню недели.', 'Соберём baseline и проверим пилот на одной кофейне.', '3 недели', 'https://example.test/nomads-demo'), makeProposal('proposal-2', 'task-2', 'team-2', 'Карта с короткими маршрутами и доступностью проходов.', 'Интервью, прототип, тестирование на первокурсниках.', '2 недели', 'https://example.test/qadam-demo', 'accepted'), makeProposal('proposal-3', 'task-3', 'team-3', 'Единый каталог с подбором по району и сезону.', 'Схема данных, MVP каталога, проверка с фермерами.', '4 недели', 'https://example.test/green-demo', 'rejected'), makeProposal('proposal-4', 'task-4', 'team-4', 'Мобильный экран с прогнозом загрузки по часам.', 'Дизайн, подключение данных, тест в спортзале.', '3 недели', 'https://example.test/nomad-mobile-demo'), makeProposal('proposal-5', 'task-5', 'team-5', 'Классификатор обращений с объяснимой подсказкой.', 'Очистка датасета, baseline, интерфейс подтверждения.', '3 недели', 'https://example.test/koktem-demo'),
  ],
};
